In [3]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [6]:
arr2 = np.array([[1,2,3,4,5]])
print(arr2.shape)
print(arr2)

(1, 5)
[[1 2 3 4 5]]


In [7]:
## 2 D array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
## attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])
print("array:\n",arr)
print("shape:",arr.shape)
print("nuber of dimensions: ",arr.ndim)
print("size(number of elements: )",arr.size)
print("data type: ",arr.dtype)
print("Item size(in bytes):",arr.itemsize)

array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
nuber of dimensions:  2
size(number of elements: ) 6
data type:  int64
Item size(in bytes): 8


In [16]:
## numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## addition
print("addition :",arr1+arr2)

# subtraction
print("sub: ",arr1-arr2)

# multiplication
print("mul :",arr1*arr2)

# division
print("div:",arr1/arr2)



addition : [11 22 33 44 55]
sub:  [ -9 -18 -27 -36 -45]
mul : [ 10  40  90 160 250]
div: [0.1 0.1 0.1 0.1 0.1]


In [17]:
## universal functions
arr = np.array([1,2,3,4,5])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [18]:
## slicing ang indexing of arrays
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
print(arr[0][0])

1


In [22]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [24]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [27]:
print(arr[0:2,1:3])

[[2 3]
 [6 7]]


In [29]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [30]:
## modify array elements
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [32]:
## statistical concepts -- normalization
# to have a mean of 0 and std deviation as 1

data = np.array([1,2,3,4,5])

# calculate mean and std dev.
mean = np.mean(data)
std_dev = np.std(data)

# normalize data
normalized_data = (data-mean)/std_dev
print("normalized data :",normalized_data)

normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [33]:
## mean , median, std,variance

data = np.array([1,2,3,4,5,6,7,8,9,10,2])

mean = np.mean(data)
print("mean :", mean)

median = np.median(data)
print("median :",median)

std=np.std(data)
print("std :",std)

var = np.var(data)
print("var :",var)

mean : 5.181818181818182
median : 5.0
std : 2.9176011883420387
var : 8.512396694214877


In [36]:
## logical operation

data = np.array([1,2,3,4,5,6,7,8,9])

data>5

data[data>5]

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])